added --salte-rating-disabled-color for colors under disabled mode
salte-io/salte-rating pull request #14
Opened 2018-06-25 15:32 UTC by christophe-g

Simple addition to have a different color when the component is on `disabled` mode.

2018-06-26 15:27 UTC, cecilia-sanare requested changes
**Couple of minor Changes**

* Change all `:host[disabled]` to `:host([disabled])`. This will fix some selectors for Polymer 2+.
* Can you also add a small demo for the disabled state with a custom color?

Otherwise it looks good to me!

2018-06-26 15:27 UTC, cecilia-sanare commented on salte-rating.html
> +      :host[disabled] .foreground-rating {
Can you change `:host[disabled]` to `:host([disabled])`?

I just noticed that this selector isn't correct for Polymer 2+.

2018-06-26 16:15 UTC, christophe-g commented on salte-rating.html
> +      :host[disabled] .foreground-rating {
Done - was not aware of `host[attribute]` not valid for Polymer 2.0. Still stuck with 1.0

Thanks for your rapid answer!

2018-06-26 16:59 UTC, nick-woodward commented on salte-rating.html
> +      :host[disabled] .foreground-rating {
Looks like you missed one of the `:host[disabled]` selectors.

2018-06-26 18:53 UTC, christophe-g commented on salte-rating.html
> +      :host[disabled] .foreground-rating {
pfff... sorry !

2018-06-27 15:52 UTC, cecilia-sanare approved these changes

2018-06-27 15:53 UTC, merged

2018-06-27 16:27 UTC, cecilia-sanare commented
Thanks for your contribution @christophe-g!

I just published your changes in [2.1.0](https://github.com/salte-io/salte-rating/releases/tag/2.1.0).